services:
    - mysql
    - postgresql
    - mongodb
    - redis
    - memcached

before_install:
    - mysql -e "CREATE DATABASE vmq_test_database;" -uroot
    - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
    - psql -c "CREATE DATABASE vmq_test_database;" -U postgres
    - psql -c "CREATE USER vmq_test_user WITH PASSWORD 'vmq_test_password';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE vmq_test_database to vmq_test_user;" -U postgres

sudo: required
dist: trusty
language: erlang
install: true
otp_release:
    - 18.3
    - 19.3
    - 20.0
before_script: "epmd -daemon"
script: "./rebar3 as all_tests do eunit, ct"
