services:
  - docker
  - mysql
  - postgresql
  - mongodb
  - redis
  - memcached

before_install:
  - sudo apt-get -y install libsnappy-dev
  - mysql -e "CREATE DATABASE vmq_test_database;" -uroot
  - mysql -e "CREATE USER 'vmq_test_user' IDENTIFIED BY 'vmq_test_password';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'vmq_test_user';" -uroot
  - psql -c "CREATE DATABASE vmq_test_database;" -U postgres
  - psql -c "CREATE USER vmq_test_user WITH PASSWORD 'vmq_test_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE vmq_test_database to vmq_test_user;" -U postgres

sudo: required
dist: trusty
language: erlang
install: true
otp_release:
  - 21.3
  - 22.0
  - 23.0
cache:
  directories:
    - plts
    - plts_base

before_script: "epmd -daemon"
script:
  - ./rebar3 as all_tests do dialyzer, eunit, ct
