services:
    - mysql
    - postgresql
    - mongodb
    - redis
    - memcached

before_install:
    - mysql -e "CREATE DATABASE test_database;" -uroot
    - mysql -e "CREATE USER 'test_user' IDENTIFIED BY 'test_password';" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'test_user';" -uroot
    - psql -c "CREATE DATABASE test_database;" -U postgres
    - psql -c "CREATE USER test_user WITH PASSWORD 'test_password';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_database to test_user;" -U postgres

sudo: required
dist: trusty
language: erlang
install: true
otp_release:
    - 19.3
    - 20.0
before_script: "epmd -daemon"
script: "./rebar3 as all_tests do eunit, ct"
